--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JuraSciix/AdvancedEvents
build-by-default: true
branches:
- master
projects:
  AdvancedEvents:
    path: ""
    model: virion
    type: library
...
