name: AdvancedEvents
description: A PocketMine-MP plugin that allows you to comfortably register events using the PHP 8 attributes.
version: 1.2
author: JuraSciix
api: [ 3.0.0, 4.0.0 ]
main: jurasciix\advancedEvents\AdvancedEvents